version: "3.8"
services:
  app:
    build: ./
    environment:
      - API_HOST=speech-recognition
      - API_PORT=8080
      - OPENAI_API_HOST=openai-speech-to-text
      - OPENAI_API_PORT=8080
      - PATH_RECORDED=/audio-files/
    volumes:
      - audio-files:/audio-files/
      - ./data:/data

  speech-recognition:
    build: ./speech-recognition
    volumes:
      - audio-files:/audio-files/

volumes:
  audio-files:
