version: "3.8"
services:
  app:
    build: ./
    environment:
      - GOOGLE_API_HOST=speech-recognition-google
      - VOSK_API_HOST=speech-recognition-vosk
      - WHISPER_API_HOST=speech-recognition-whisper
      - API_PORT=8080
      - OPENAI_API_HOST=openai-speech-to-text
      - OPENAI_API_PORT=8080
      - PATH_RECORDED=/audio-files/
    volumes:
      - audio-files:/audio-files/
      - ./data:/data
    restart: always

  speech-recognition-google:
    build: ./speech-recognition
    volumes:
      - audio-files:/audio-files/
    restart: always

  speech-recognition-vosk:
    build: ./speech-recognition
    volumes:
      - audio-files:/audio-files/
    restart: always

  speech-recognition-whisper:
    build: ./speech-recognition
    volumes:
      - audio-files:/audio-files/
    restart: always

volumes:
  audio-files:
