version: "3.8"
services:
  recorder:
    build: ./recorder
    volumes:
      - ./data/:/data/
    init: true
    restart: always

  recognizer:
    build: ./recognizer
    volumes:
      - ./data/:/data/
    init: true
    restart: always
