version: "3.8"

services:
  watcher:
    build: ./watcher
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: ./settings/
        target: /app/settings/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      RECOGNIZER_HEADLESS: false
      RECOGNIZER_DISPLAY: 192.168.0.101:0.0
    networks:
      - chatwatcher-network
    restart: always

  web:
    build: ./web
    environment:
      NGINX_SERVER_NAME: web
      NGINX_HSTS_MAX_AGE: 31536000
    volumes:
      - certs:/etc/ssl/certs/nginx:ro,cached
    depends_on:
      cert:
        condition: service_completed_successfully
    networks:
      - chatwatcher-network
    restart: always

  cert:
    build: ./cert
    environment:
      DOMAIN: web
    volumes:
      - certs:/app:delegated

networks:
  chatwatcher-network:
    external: true

volumes:
  certs:
