# Maven でビルド・テストを実行する

name: Maven CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build with Maven (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
        distribution: [ adopt ]
        target: [ 'recorder', 'recognizer' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.target }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.target }}

      - name: Build with Maven
        working-directory: ${{ matrix.target }}
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ matrix.target }}/target/*.jar